databases:
  - name: gcs-db
    plan: free

services:
  - type: web
    name: buster-code-challenge
    env: ruby
    buildCommand: |
      bundle install
      npm install
      bundle exec rake assets:precompile
      bundle exec rake db:migrate
      bundle exec rake db:seed
    startCommand: bundle exec rails server
    envVars:
      - key: RAILS_MASTER_KEY
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: gcs-db
          property: connectionString

