databases:
  - name: gcs
    databaseName: gcs
    user: gcs
    plan: free

services:
  - type: web
    name gcs
    runtime: ruby
    plan: free
    buildcommand: "./bin/render-build.sh"
    startCommand: ".bin/dev"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gcs
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync:false- key: WEB_CONCURRENCY
        value: 2

